version: "3"
services:
  couchbase:
    image: couchbase
    expose:
      - "8091"
      - "8092"
      - "8093"
      - "8094"
      - "11210"
    ports:
      - "8091:8091"
    environment:
      - USERNAME=admin
      - PASSWORD=gnomes
    volumes:
      - C:/docker/couchbase:/opt/couchbase/var
  invoice-microservice:
    image: vertx-intranet/invoice-microservice
    links:
      - couchbase
    depends_on:
      - couchbase
    ports:
      - "8081:8081"
